// ═══════════════════════════════════════════════
//  TEAM DATA — Player quality, form, records
// ═══════════════════════════════════════════════
const TEAMS = {
  FRA: { name:"France",      flag:"🇫🇷",
    stats:{atk:94,mid:90,def:92,gk:88,form:85,depth:92,exp:95},
    players:["Kylian Mbappé","Tchouaméni","William Saliba","Mike Maignan"],
    record:"8W-1D-1L", history:"WC 2018 Champion · Final 2022",
    edge:"Mbappé (ATK 94) + elite defensive block; Maignan world-class GK" },
  ESP: { name:"Spain",       flag:"🇪🇸",
    stats:{atk:88,mid:95,def:87,gk:83,form:90,depth:91,exp:88},
    players:["Pedri","Rodri","Lamine Yamal","Álvaro Morata"],
    record:"9W-1D-0L", history:"WC 2010 · Euro 2024 Champions",
    edge:"Highest midfield (95) — Rodri + Pedri suffocate any opponent" },
  ARG: { name:"Argentina",   flag:"🇦🇷",
    stats:{atk:93,mid:87,def:85,gk:92,form:82,depth:86,exp:96},
    players:["Lionel Messi","Emiliano Martínez","Mac Allister","C. Romero"],
    record:"7W-2D-1L", history:"WC 2022 Champion · Final 2014",
    edge:"Emiliano Martínez (GK 92) — best WC GK ever; Messi's last WC" },
  ENG: { name:"England",     flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    stats:{atk:89,mid:88,def:84,gk:86,form:78,depth:88,exp:78},
    players:["Jude Bellingham","Harry Kane","Bukayo Saka","Declan Rice"],
    record:"6W-2D-2L", history:"SF 2018 · Euro Final 2024",
    edge:"Bellingham + Kane: world's most dangerous 1-2 combination" },
  BRA: { name:"Brazil",      flag:"🇧🇷",
    stats:{atk:93,mid:86,def:85,gk:87,form:75,depth:91,exp:89},
    players:["Vinícius Jr.","Rodrygo","Alisson Becker","Marquinhos"],
    record:"6W-2D-2L", history:"QF 2022 · WC 2002 (last title)",
    edge:"Vinícius is world's most dangerous attacker 2025; historic depth" },
  POR: { name:"Portugal",    flag:"🇵🇹",
    stats:{atk:87,mid:86,def:83,gk:83,form:80,depth:84,exp:85},
    players:["Bruno Fernandes","Rafael Leão","Rúben Dias","João Neves"],
    record:"7W-1D-2L", history:"QF 2022 · SF 2006",
    edge:"Post-Ronaldo resurgence: Leão + young João Neves in midfield" },
  GER: { name:"Germany",     flag:"🇩🇪",
    stats:{atk:88,mid:85,def:84,gk:86,form:77,depth:87,exp:90},
    players:["Florian Wirtz","Jamal Musiala","Antonio Rüdiger","ter Stegen"],
    record:"6W-2D-2L", history:"WC 2014 · Euro 2024 QF host",
    edge:"Wirtz + Musiala = most exciting young midfield in world football" },
  MAR: { name:"Morocco",     flag:"🇲🇦",
    stats:{atk:80,mid:82,def:89,gk:87,form:82,depth:80,exp:78},
    players:["Achraf Hakimi","Yassine Bounou","Sofyan Amrabat","En-Nesyri"],
    record:"7W-1D-2L", history:"SF 2022 (historic run) · AFCON finalist",
    edge:"Elite defensive block (89) + Bounou's WC saves; giant-killers" },
  USA: { name:"USA",         flag:"🇺🇸",
    stats:{atk:76,mid:79,def:76,gk:78,form:74,depth:80,exp:68},
    players:["Christian Pulisic","Gio Reyna","Matt Turner","Tyler Adams"],
    record:"5W-2D-3L", history:"Co-host · R16 2022",
    edge:"Home advantage in front of massive crowds; Pulisic leading charge" },
  NED: { name:"Netherlands", flag:"🇳🇱",
    stats:{atk:85,mid:84,def:83,gk:84,form:76,depth:84,exp:82},
    players:["Virgil van Dijk","Cody Gakpo","Frenkie de Jong","Dumfries"],
    record:"6W-1D-3L", history:"SF 2014 · Final 2010",
    edge:"Van Dijk + de Jong world-class spine; Gakpo clinical in 2024-25" },
  COL: { name:"Colombia",    flag:"🇨🇴",
    stats:{atk:84,mid:83,def:80,gk:80,form:79,depth:82,exp:72},
    players:["Luis Díaz","James Rodríguez","Daniel Muñoz","D. Sánchez"],
    record:"7W-1D-2L", history:"Copa América 2024 runner-up",
    edge:"Luis Díaz in peak form; Copa América mentality proven" },
  URU: { name:"Uruguay",     flag:"🇺🇾",
    stats:{atk:82,mid:80,def:84,gk:82,form:75,depth:78,exp:84},
    players:["Federico Valverde","Darwin Núñez","Araújo","Olivera"],
    record:"5W-3D-2L", history:"SF 2010",
    edge:"Valverde (world's best box-to-box) + Núñez power; gritty DNA" },
  JPN: { name:"Japan",       flag:"🇯🇵",
    stats:{atk:80,mid:83,def:80,gk:80,form:80,depth:80,exp:72},
    players:["Kaoru Mitoma","Doan","Ko Itakura","Wataru Endō"],
    record:"7W-1D-2L", history:"R16 2022 · Beat Germany & Spain in groups",
    edge:"Disciplined pressing system; proven giant-killers when it clicks" },
  BEL: { name:"Belgium",     flag:"🇧🇪",
    stats:{atk:82,mid:82,def:80,gk:81,form:72,depth:80,exp:82},
    players:["Kevin De Bruyne","Romelu Lukaku","Thibaut Courtois","Tielemans"],
    record:"5W-2D-3L", history:"SF 2018 (golden gen swan song)",
    edge:"De Bruyne's vision at 34; Courtois single-handedly wins games" },
  CRO: { name:"Croatia",     flag:"🇭🇷",
    stats:{atk:79,mid:86,def:81,gk:80,form:72,depth:76,exp:88},
    players:["Luka Modrić","Mateo Kovačić","Joško Gvardiol","Kramarić"],
    record:"5W-2D-3L", history:"WC Final 2018 · SF 2022",
    edge:"Modrić's final WC — tournament-hardened experience (88); Gvardiol" },
  SEN: { name:"Senegal",     flag:"🇸🇳",
    stats:{atk:80,mid:78,def:80,gk:83,form:75,depth:76,exp:72},
    players:["Sadio Mané","Édouard Mendy","Idrissa Gueye","Jakobs"],
    record:"6W-1D-3L", history:"AFCON 2022 Champions · R16 2022",
    edge:"Mendy's world-class shot-stopping; AFCON winning mentality" },
};

// ─── R16 BRACKET ───
// Left half → Semi-Final 1 | Right half → Semi-Final 2
const R16 = [
  { id:0, half:"L", t1:"FRA", t2:"SEN",  label:"R16 — A" },
  { id:1, half:"L", t1:"GER", t2:"USA",  label:"R16 — B" },
  { id:2, half:"L", t1:"ESP", t2:"JPN",  label:"R16 — C" },
  { id:3, half:"L", t1:"MAR", t2:"NED",  label:"R16 — D" },
  { id:4, half:"R", t1:"ARG", t2:"COL",  label:"R16 — E" },
  { id:5, half:"R", t1:"BRA", t2:"URU",  label:"R16 — F" },
  { id:6, half:"R", t1:"ENG", t2:"CRO",  label:"R16 — G" },
  { id:7, half:"R", t1:"POR", t2:"BEL",  label:"R16 — H" },
];

// ─── STAT METADATA ───
const STAT_META = {
  atk:  { label:"ATK",  color:"#f97316" },
  mid:  { label:"MID",  color:"#a78bfa" },
  def:  { label:"DEF",  color:"#22d3ee" },
  gk:   { label:"GK",   color:"#facc15" },
  form: { label:"FORM", color:"#4ade80" },
  depth:{ label:"DPTH", color:"#60a5fa" },
  exp:  { label:"EXP",  color:"#f472b6" },
};

// ─── OVERALL RATING ───
function overallRating(id) {
  const s = TEAMS[id].stats;
  return Math.round(
    s.atk   * 0.22 +
    s.mid   * 0.20 +
    s.def   * 0.20 +
    s.gk    * 0.10 +
    s.form  * 0.15 +
    s.exp   * 0.08 +
    s.depth * 0.05
  );
}

// ─── PLAYER DETAIL DATA ───
const PLAYER_DATA = {
  FRA: [
    { name:"Kylian Mbappé",    club:"Real Madrid",    initials:"KM", role:"ATK",   rating:97, color:"#2979ff",
      desc:"Fastest player at the tournament (38km/h). Created 0.72 xG per 90 in 2024-25. Becomes unstoppable in transition — 2 touches, 1 goal." },
    { name:"Mike Maignan",     club:"AC Milan",       initials:"MM", role:"GK",    rating:90, color:"#1565c0",
      desc:"Replaced Lloris and never looked back. 0.18 PSxG−xG in 24-25 — saves shots others don't reach. Critical in tight KO games." },
    { name:"Aurélien Tchouaméni", club:"Real Madrid", initials:"AT", role:"MID",   rating:88, color:"#1976d2",
      desc:"Covers 12.2km per game. Wins 68% of ground duels. The engine that lets Mbappé play forward without defensive risk." },
    { name:"William Saliba",   club:"Arsenal",        initials:"WS", role:"DEF",   rating:89, color:"#0d47a1",
      desc:"Best CB in the Premier League 24-25. 91% pass accuracy from deep. Reads danger before it materialises." },
  ],
  ESP: [
    { name:"Rodri",            club:"Man City",        initials:"RO", role:"MID",  rating:96, color:"#c62828",
      desc:"The metronome. 94% pass accuracy, wins possession back in 3.1 seconds avg. Controls entire match tempo single-handedly." },
    { name:"Pedri",            club:"Barcelona",       initials:"PE", role:"MID",  rating:92, color:"#b71c1c",
      desc:"1,200+ completed passes in 24-25. Finds pockets of space others don't see. Unlocks defensive blocks with one-touch triangles." },
    { name:"Lamine Yamal",     club:"Barcelona",       initials:"LY", role:"ATK",  rating:91, color:"#d32f2f",
      desc:"18 years old. Already Europe's most electric wideman. 1v1 success rate of 73% — forces every team to double up, creating space for Morata." },
    { name:"Álvaro Morata",    club:"Atletico Madrid", initials:"AM", role:"FWD",  rating:85, color:"#e53935",
      desc:"The perfect counterpart to Spain's build-up system. Movement off the ball drags centre-backs out of shape. Clinical when fed." },
  ],
  ARG: [
    { name:"Lionel Messi",     club:"Inter Miami",     initials:"LM", role:"ATK",  rating:95, color:"#1b5e20",
      desc:"Statistically declining but tournament-level Messi is different. 1.12 xA per 90 from set pieces alone. His last WC creates a ceiling-lift nobody can model." },
    { name:"Emiliano Martínez",club:"Aston Villa",     initials:"EM", role:"GK",   rating:92, color:"#2e7d32",
      desc:"Best WC goalkeeper in history. 9 saves in 2022 KO rounds including a penalty-shootout stop that won the trophy. Elite at destabilising penalty takers." },
    { name:"Alexis Mac Allister",club:"Liverpool",     initials:"MA", role:"MID",  rating:88, color:"#388e3c",
      desc:"Liverpool's best midfielder in 24-25. Press-resistant, arrives late into the box (7 goals). Fills the role Messi vacated in midfield." },
    { name:"Cristian Romero",  club:"Tottenham",       initials:"CR", role:"DEF",  rating:87, color:"#43a047",
      desc:"Aggressive, dominant in duels (73% win rate). The defensive anchor who allows Messi to roam freely without defensive liability." },
  ],
  ENG: [
    { name:"Jude Bellingham",  club:"Real Madrid",     initials:"JB", role:"MID",  rating:94, color:"#bf360c",
      desc:"23 goals from midfield in 24-25 La Liga. Arrives in the box like a striker, defends like a 6. The most complete midfielder at the tournament." },
    { name:"Harry Kane",       club:"Bayern Munich",   initials:"HK", role:"FWD",  rating:92, color:"#e64a19",
      desc:"36 Bundesliga goals in 24-25. Drops deep to create for Bellingham and Saka, then arrives in the box late. Unstoppable combination." },
    { name:"Bukayo Saka",      club:"Arsenal",         initials:"BS", role:"ATK",  rating:91, color:"#f4511e",
      desc:"19 goals + 16 assists in 24-25. Right side of England's attack is world-class. Creates more from the right than any other winger in Europe." },
    { name:"Declan Rice",      club:"Arsenal",         initials:"DR", role:"MID",  rating:89, color:"#ff5722",
      desc:"Arsenal's captain. Breaks up 8.4 attacks per 90. Allows Bellingham to play forward by handling defensive transition single-handedly." },
  ],
  BRA: [
    { name:"Vinícius Jr.",     club:"Real Madrid",     initials:"VJ", role:"ATK",  rating:95, color:"#f9a825",
      desc:"World's most dangerous attacker in 2025. 31 goals in La Liga. No defender one-on-one can stop him. Makes Brazil genuinely scary." },
    { name:"Rodrygo",          club:"Real Madrid",     initials:"RO", role:"ATK",  rating:89, color:"#f57f17",
      desc:"The perfect partner for Vinícius — quieter but clinical. Scored in every KO game for Real Madrid in 24-25 UCL." },
    { name:"Alisson Becker",   club:"Liverpool",       initials:"AB", role:"GK",   rating:91, color:"#e65100",
      desc:"Liverpool's undroppable. Distribution at 96% accuracy makes Brazil an extra outfield player in build-up. Shot-stopping elite." },
    { name:"Marquinhos",       club:"PSG",             initials:"MQ", role:"DEF",  rating:88, color:"#bf360c",
      desc:"Captain. Leads by example in every duel. The constant in Brazil's defence regardless of coach or system since 2018." },
  ],
  POR: [
    { name:"Bruno Fernandes",  club:"Man United",      initials:"BF", role:"MID",  rating:90, color:"#880e4f",
      desc:"Post-Ronaldo Portugal's spiritual leader. 22 goals + 17 assists in 24-25 PL. Dictates tempo with his runs from deep." },
    { name:"Rafael Leão",      club:"AC Milan",        initials:"RL", role:"ATK",  rating:89, color:"#ad1457",
      desc:"The new spearhead. Explosive over 10 metres. In 24-25 was Serie A's most direct attacker — defence must always account for him first." },
    { name:"Rúben Dias",       club:"Man City",        initials:"RD", role:"DEF",  rating:90, color:"#c2185b",
      desc:"PL's best CB in 24-25. Aerial dominance (87% win rate). Portugal's defensive backbone who allows attacking fullbacks to maraud forward." },
    { name:"João Neves",       club:"PSG",             initials:"JN", role:"MID",  rating:87, color:"#e91e63",
      desc:"21 years old, already PSG's midfield anchor. Covers ground Pedri-style. Portugal's future — and very much their present." },
  ],
  GER: [
    { name:"Florian Wirtz",    club:"B. Leverkusen",   initials:"FW", role:"ATK",  rating:93, color:"#212121",
      desc:"24 goals + 18 assists in 24-25 Bundesliga. Dribbles through pressure with ease. Germany's creative engine — if he fires, anything is possible." },
    { name:"Jamal Musiala",    club:"Bayern Munich",   initials:"JM", role:"MID",  rating:91, color:"#424242",
      desc:"The most complete young midfielder in world football. Can play anywhere across the front 6. Won't be stopped by tactics — only by legs." },
    { name:"Antonio Rüdiger",  club:"Real Madrid",     initials:"AR", role:"DEF",  rating:87, color:"#616161",
      desc:"Commanding, aggressive, wins everything in the air. Rüdiger vs Vinícius/Mbappé is the biggest defensive test at the tournament." },
    { name:"Marc ter Stegen",  club:"Barcelona",       initials:"TS", role:"GK",   rating:86, color:"#757575",
      desc:"World-class reflexes. Has prevented 7 'certain' goals in 24-25 per xG models. Germany's last line of defence in every sense." },
  ],
  MAR: [
    { name:"Achraf Hakimi",    club:"PSG",             initials:"AH", role:"DEF",  rating:90, color:"#004d40",
      desc:"World's best attacking right-back. 14 assists from fullback in 24-25 Ligue 1. Causes matchup nightmares — is he a winger or a defender?" },
    { name:"Yassine Bounou",   club:"Al-Hilal",        initials:"YB", role:"GK",   rating:89, color:"#00695c",
      desc:"The 2022 WC's best goalkeeper statistically. 4 clean sheets in 5 KO games. Morocco's foundation — without him, the 2022 run doesn't happen." },
    { name:"Sofyan Amrabat",   club:"Fiorentina",      initials:"SA", role:"MID",  rating:85, color:"#00796b",
      desc:"Broke up 9.2 attacks per 90 at 2022 WC. The destroyer who makes Morocco unplayable to press. Underrated globally, known to every top team." },
    { name:"Youssef En-Nesyri",club:"Fenerbahce",      initials:"YE", role:"FWD",  rating:84, color:"#00897b",
      desc:"Aerial threat (headed 3 WC goals in 2022). The target man who holds play up and creates space for Hakimi's overlaps." },
  ],
  JPN: [
    { name:"Kaoru Mitoma",     club:"Brighton",        initials:"KM", role:"ATK",  rating:87, color:"#1a237e",
      desc:"The 2022 WC hero. His low cross for Japan's winner vs Spain in 2022 that wasn't out. Clinical in transition. Europe's most underrated winger." },
    { name:"Daichi Kamada",    club:"Lazio",           initials:"DK", role:"MID",  rating:84, color:"#283593",
      desc:"Roaming 10 who creates from deep. Scored Japan's winner vs Germany in 2022. Arrives late into the box without being tracked." },
    { name:"Ko Itakura",       club:"B. Mönchengladbach",initials:"KI",role:"DEF",rating:83, color:"#303f9f",
      desc:"Organises Japan's defensive shape. The communication hub in their low block — Japan's 2022 run was built on his reading of the game." },
    { name:"Wataru Endō",      club:"Liverpool",       initials:"WE", role:"MID",  rating:85, color:"#3949ab",
      desc:"Liverpool starter. Press-triggering system relies on his positioning. Against Spain's Rodri, this is Japan's biggest tactical battle." },
  ],
  USA: [
    { name:"Christian Pulisic",club:"AC Milan",        initials:"CP", role:"ATK",  rating:86, color:"#b71c1c",
      desc:"Serie A's best American export. 17 goals in 24-25. Home crowd supercharges his performance. The face and heartbeat of USMNT." },
    { name:"Gio Reyna",        club:"B. Dortmund",     initials:"GR", role:"MID",  rating:83, color:"#c62828",
      desc:"When fit, a genuine world-class talent. Injury-prone but electric. USA's ceiling rises dramatically when Reyna is at 100%." },
    { name:"Matt Turner",      club:"Crystal Palace",  initials:"MT", role:"GK",   rating:81, color:"#d32f2f",
      desc:"Shot-stopping above average for his level. Home crowd creates fortress atmosphere. USA's shield in a tournament where upsets are possible." },
    { name:"Tyler Adams",      club:"Bournemouth",     initials:"TA", role:"MID",  rating:82, color:"#e53935",
      desc:"The captain. Tenacious, 8.9 ball recoveries per 90. Sets the tone defensively — without him USA's entire midfield press collapses." },
  ],
  NED: [
    { name:"Virgil van Dijk",  club:"Liverpool",       initials:"VV", role:"DEF",  rating:92, color:"#e65100",
      desc:"Still the world's best CB by dominance. 91% aerial duel win rate in 24-25. Brings calm to everything around him — the Netherlands' captain." },
    { name:"Cody Gakpo",       club:"Liverpool",       initials:"CG", role:"ATK",  rating:88, color:"#bf360c",
      desc:"25 goals in 24-25 PL. Clinical from any position. Netherlands are a different team when Gakpo is on — he creates overloads just by his movement." },
    { name:"Frenkie de Jong",  club:"Barcelona",       initials:"FJ", role:"MID",  rating:87, color:"#d84315",
      desc:"The heartbeat of Netherlands. Carries from deep, presses high, arrives late. Barcelona's best player again after injury recovery." },
    { name:"Denzel Dumfries",  club:"Inter Milan",     initials:"DD", role:"DEF",  rating:86, color:"#e64a19",
      desc:"Best attacking fullback in Serie A 24-25. His partnership with Gakpo on the right creates the Netherlands' most productive avenue." },
  ],
  COL: [
    { name:"Luis Díaz",        club:"Liverpool",       initials:"LD", role:"ATK",  rating:89, color:"#f57f17",
      desc:"Liverpool's most dangerous forward in 24-25. 21 goals. Pacy, direct and two-footed. Has the ability to beat tournament heavyweights alone." },
    { name:"James Rodríguez",  club:"Rayo Vallecano",  initials:"JR", role:"MID",  rating:84, color:"#f9a825",
      desc:"The artist. Still controls matches with his left foot at 34. Must stay fit — Colombia are a different team with James pulling the strings." },
    { name:"Daniel Muñoz",     club:"Crystal Palace",  initials:"DM", role:"DEF",  rating:84, color:"#fbc02d",
      desc:"PL standout. Overlapping right-back who created 11 chances in 24-25. Colombia's set-piece specialist and the unlocking mechanism on the right." },
    { name:"David Ospina",     club:"Al-Qadsiah",      initials:"DO", role:"GK",   rating:83, color:"#f57f17",
      desc:"Veteran presence. Kept Colombia organised in Copa América 2024. His experience handling high-pressure KO games is irreplaceable." },
  ],
  URU: [
    { name:"Federico Valverde",club:"Real Madrid",     initials:"FV", role:"MID",  rating:92, color:"#1a237e",
      desc:"The world's best box-to-box midfielder. Covers 13km per match. Wins the ball and immediately creates — the perfect engine for Uruguay's counter-press." },
    { name:"Darwin Núñez",     club:"Liverpool",       initials:"DN", role:"FWD",  rating:87, color:"#283593",
      desc:"Raw power, relentless movement. 19 PL goals in 24-25. Defenders hate playing against him physically — he never gives them rest." },
    { name:"Ronald Araújo",    club:"Barcelona",       initials:"RA", role:"DEF",  rating:88, color:"#303f9f",
      desc:"La Liga's most dominant CB in duels (78% win). Saved Barcelona's season twice with last-ditch blocks. Uruguay's defensive pillar." },
    { name:"Mathías Olivera",  club:"Napoli",          initials:"MO", role:"DEF",  rating:84, color:"#3949ab",
      desc:"Left-back who operates like a winger. Links seamlessly with Núñez on the left, creating Uruguay's most direct attacking channel." },
  ],
  BEL: [
    { name:"Kevin De Bruyne",  club:"Man City",        initials:"KD", role:"MID",  rating:91, color:"#311b92",
      desc:"At 34, still seeing the game 3 seconds ahead. 22 assists in 24-25 PL. If Belgium go deep, it's because KDB has found space others can't." },
    { name:"Romelu Lukaku",    club:"Napoli",          initials:"RL", role:"FWD",  rating:87, color:"#4527a0",
      desc:"24 Serie A goals. Physical presence causes problems for every defence. When De Bruyne finds Lukaku in the final third, it's nearly always dangerous." },
    { name:"Thibaut Courtois", club:"Real Madrid",     initials:"TC", role:"GK",   rating:91, color:"#512da8",
      desc:"After his ACL return, arguably the best GK in world football again. His UCL 22-23 performance was the greatest single-match GK display ever." },
    { name:"Youri Tielemans",  club:"Aston Villa",     initials:"YT", role:"MID",  rating:85, color:"#5e35b1",
      desc:"The engine behind De Bruyne. Press-resistant, covers ground. Belgium miss him most when he's absent — the quiet architect of their midfield." },
  ],
  CRO: [
    { name:"Luka Modrić",      club:"Real Madrid",     initials:"LM", role:"MID",  rating:90, color:"#b71c1c",
      desc:"The greatest WC midfielder of all time. This is his final WC. Motivated beyond data. Has beaten Argentina, England and Brazil in previous WCs." },
    { name:"Mateo Kovačić",    club:"Man City",        initials:"MK", role:"MID",  rating:87, color:"#c62828",
      desc:"PL champion. Takes the pressure off Modrić by doing the dirty work. The most underrated player at this WC — quietly excellent in every match." },
    { name:"Joško Gvardiol",   club:"Man City",        initials:"JG", role:"DEF",  rating:89, color:"#d32f2f",
      desc:"22 years old, already world-class. PL best CB under 25 in 24-25. Croatia's defensive anchor who enables the midfield to play without fear." },
    { name:"Andrej Kramarić",  club:"Hoffenheim",      initials:"AK", role:"FWD",  rating:84, color:"#e53935",
      desc:"Croatia's most reliable goalscorer. 18 Bundesliga goals. Always available when the midfield needs a release valve in tight KO games." },
  ],
  SEN: [
    { name:"Sadio Mané",       club:"Al Nassr",        initials:"SM", role:"ATK",  rating:87, color:"#004d40",
      desc:"Slower than his Liverpool peak but still lethal in the final third. His leadership transforms Senegal's mentality in big moments." },
    { name:"Édouard Mendy",    club:"Al-Ahly",         initials:"EM", role:"GK",   rating:86, color:"#00695c",
      desc:"AFCON-winning GK. Kept 4 clean sheets at 2022 WC. His shot-stopping is Senegal's equaliser against technically superior opposition." },
    { name:"Idrissa Gueye",    club:"Everton",         initials:"IG", role:"MID",  rating:84, color:"#00796b",
      desc:"The destroyer at the base. 10.1 ball recoveries per 90. Creates a defensive wall that lets Senegal play without midfield exposure." },
    { name:"Ismail Jakobs",    club:"Monaco",          initials:"IJ", role:"DEF",  rating:82, color:"#00897b",
      desc:"Left-back with attacking intent. Overlaps with Mané to create Senegal's best wide channel. A threat England and France must account for." },
  ],
};

// Threat level (1-5) for each team
const THREAT = { FRA:5, ESP:5, ARG:5, ENG:4, BRA:4, POR:4, GER:3, MAR:3, URU:2, NED:2, COL:2, JPN:2, BEL:2, CRO:2, SEN:1, USA:1 };

// Knockout path probabilities
const KO_PATH = {
  FRA:[{stage:'R16',vs:'Senegal',pct:92.5},{stage:'QF',vs:'Germany',pct:76.5},{stage:'SF',vs:'Spain',pct:59.8}],
  ESP:[{stage:'R16',vs:'Japan',pct:86.3},{stage:'QF',vs:'Morocco',pct:75.2},{stage:'SF',vs:'France',pct:40.2}],
  ARG:[{stage:'R16',vs:'Colombia',pct:84.0},{stage:'QF',vs:'Brazil',pct:62.1},{stage:'SF',vs:'England',pct:69.3}],
  ENG:[{stage:'R16',vs:'Croatia',pct:71.0},{stage:'QF',vs:'Portugal',pct:52.7},{stage:'SF',vs:'Argentina',pct:30.7}],
  BRA:[{stage:'R16',vs:'Uruguay',pct:66.8},{stage:'QF',vs:'Argentina',pct:37.9},{stage:'SF',vs:'England',pct:42.1}],
  POR:[{stage:'R16',vs:'Belgium',pct:60.2},{stage:'QF',vs:'England',pct:47.3},{stage:'SF',vs:'Argentina',pct:36.2}],
  GER:[{stage:'R16',vs:'USA',pct:71.3},{stage:'QF',vs:'France',pct:23.5},{stage:'SF',vs:'Spain',pct:38.0}],
  MAR:[{stage:'R16',vs:'Netherlands',pct:55.1},{stage:'QF',vs:'Spain',pct:24.8},{stage:'SF',vs:'France',pct:28.0}],
};
