// ═══════════════════════════════════════════════
//  COMPREHENSIVE MATCH ODDS — WC 2026
//  Sources: Bet365, Pinnacle, FanDuel, William Hill
//  AH = Asian Handicap | 水位 = Payout rate
//  Updated: June 8 2026
// ═══════════════════════════════════════════════

// Player key icons per team (initials + color for avatar)
const KEY_PLAYERS = {
  FRA:[{init:"KM",name:"Mbappé",role:"ATK",col:"#2979ff"},{init:"MM",name:"Maignan",role:"GK",col:"#1565c0"},{init:"WS",name:"Saliba",role:"DEF",col:"#0d47a1"}],
  ESP:[{init:"RO",name:"Rodri",role:"MID",col:"#c62828"},{init:"PE",name:"Pedri",role:"MID",col:"#b71c1c"},{init:"LY",name:"Yamal",role:"ATK",col:"#d32f2f"}],
  ARG:[{init:"LM",name:"Messi",role:"ATK",col:"#1b5e20"},{init:"EM",name:"E.Martínez",role:"GK",col:"#2e7d32"},{init:"CR",name:"Romero",role:"DEF",col:"#388e3c"}],
  ENG:[{init:"JB",name:"Bellingham",role:"MID",col:"#bf360c"},{init:"HK",name:"Kane",role:"FWD",col:"#e64a19"},{init:"BS",name:"Saka",role:"ATK",col:"#f4511e"}],
  BRA:[{init:"VJ",name:"Vinícius",role:"ATK",col:"#f9a825"},{init:"RO",name:"Rodrygo",role:"ATK",col:"#f57f17"},{init:"AB",name:"Alisson",role:"GK",col:"#e65100"}],
  POR:[{init:"BF",name:"B.Fernandes",role:"MID",col:"#880e4f"},{init:"RL",name:"Leão",role:"ATK",col:"#ad1457"},{init:"RD",name:"R.Dias",role:"DEF",col:"#c2185b"}],
  GER:[{init:"FW",name:"Wirtz",role:"ATK",col:"#212121"},{init:"JM",name:"Musiala",role:"MID",col:"#424242"},{init:"AR",name:"Rüdiger",role:"DEF",col:"#616161"}],
  MAR:[{init:"AH",name:"Hakimi",role:"DEF",col:"#004d40"},{init:"YB",name:"Bounou",role:"GK",col:"#00695c"},{init:"SA",name:"Amrabat",role:"MID",col:"#00796b"}],
  NED:[{init:"VV",name:"Van Dijk",role:"DEF",col:"#e65100"},{init:"CG",name:"Gakpo",role:"ATK",col:"#bf360c"},{init:"FJ",name:"De Jong",role:"MID",col:"#d84315"}],
  URU:[{init:"FV",name:"Valverde",role:"MID",col:"#1a237e"},{init:"DN",name:"Núñez",role:"FWD",col:"#283593"},{init:"RA",name:"Araújo",role:"DEF",col:"#303f9f"}],
  BEL:[{init:"KD",name:"De Bruyne",role:"MID",col:"#311b92"},{init:"RL",name:"Lukaku",role:"FWD",col:"#4527a0"},{init:"TC",name:"Courtois",role:"GK",col:"#512da8"}],
  CRO:[{init:"LM",name:"Modrić",role:"MID",col:"#b71c1c"},{init:"JG",name:"Gvardiol",role:"DEF",col:"#c62828"},{init:"MK",name:"Kovačić",role:"MID",col:"#d32f2f"}],
  SEN:[{init:"SM",name:"Mané",role:"ATK",col:"#004d40"},{init:"EM",name:"Mendy",role:"GK",col:"#00695c"},{init:"IG",name:"Gueye",role:"MID",col:"#00796b"}],
  JPN:[{init:"KM",name:"Mitoma",role:"ATK",col:"#1a237e"},{init:"WE",name:"Endō",role:"MID",col:"#283593"},{init:"KI",name:"Itakura",role:"DEF",col:"#303f9f"}],
  COL:[{init:"LD",name:"L.Díaz",role:"ATK",col:"#f57f17"},{init:"JR",name:"James",role:"MID",col:"#f9a825"},{init:"DM",name:"Muñoz",role:"DEF",col:"#fbc02d"}],
  USA:[{init:"CP",name:"Pulisic",role:"ATK",col:"#b71c1c"},{init:"GR",name:"Reyna",role:"MID",col:"#c62828"},{init:"TA",name:"Adams",role:"MID",col:"#d32f2f"}],
};

// ── STAGES ──
const STAGE = { GRP:"Group Stage", R32:"Round of 32", R16:"Round of 16", QF:"Quarter-Final", SF:"Semi-Final", F:"Final" };

const MATCHES = [

  // ══════════════════════════════════════════════════════
  //  GROUP STAGE — ROUND 1 (Jun 11–17)
  // ══════════════════════════════════════════════════════

  { id:"A1", stage:"GRP", date:"Jun 11", group:"Group A", venue:"Mexico City",
    home:"Mexico", homeFlag:"🇲🇽", homeCode:"MEX",
    away:"South Africa", awayFlag:"🇿🇦", awayCode:"RSA",
    homeML:-350, awayML:320,
    ah:{ line:-1.25, homeLabel:"MEX -1.25", awayLabel:"RSA +1.25", homePayout:1.85, awayPayout:1.95 },
    simHomeWin:74, simCoverAH:55, marketCoverAH:51, edge:4,
    notes:"Mexico 74% to win at home Azteca. Model score 2-0 — a two-goal margin covers -1.25 in full.",
    rec:"slight", recLabel:"✓ Back MEX -1.25", recDetail:"Model 2-0: Mexico covers -1.25 in 55% of outcomes — modest edge on the favourite." },

  { id:"A2", stage:"GRP", date:"Jun 11", group:"Group A", venue:"Guadalajara",
    home:"Korea Republic", homeFlag:"🇰🇷", homeCode:"KOR",
    away:"Czechia", awayFlag:"🇨🇿", awayCode:"CZE",
    homeML:180, awayML:210,
    ah:{ line:0, homeLabel:"KOR 0", awayLabel:"CZE 0", homePayout:1.9, awayPayout:1.9 },
    simHomeWin:44, simCoverAH:44, marketCoverAH:50, edge:-6,
    notes:"Balanced match. Czechia slight sim edge. DNB at 0 — draw refunds stake.",
    rec:"value", recLabel:"✓ Back CZE 0", recDetail:"Underdog covers 56% of the time — value on CZE 0." },

  { id:"C1", stage:"GRP", date:"Jun 13", group:"Group C", venue:"East Rutherford NJ",
    home:"Brazil", homeFlag:"🇧🇷", homeCode:"BRA", homePlayers:["BRA"],
    away:"Morocco", awayFlag:"🇲🇦", awayCode:"MAR", awayPlayers:["MAR"],
    homeML:-350, awayML:320,
    ah:{ line:-1, homeLabel:"BRA -1", awayLabel:"MAR +1.0", homePayout:2.21, awayPayout:1.73 },
    simHomeWin:70, simCoverAH:33, marketCoverAH:44, edge:-11,
    notes:"Morocco DEF 89 + Bounou GK 87 = elite defensive block. Brazil 70% win but only 44% to win by 2+.",
    rec:"strong", recLabel:"🔥 Back MAR +1.0", recDetail:"Underdog covers 67% — strong value on MAR." },

  { id:"D1", stage:"GRP", date:"Jun 12", group:"Group D", venue:"Los Angeles",
    home:"USA", homeFlag:"🇺🇸", homeCode:"USA", homePlayers:["USA"],
    away:"Paraguay", awayFlag:"🇵🇾", awayCode:"PAR",
    homeML:130, awayML:340,
    ah:{ line:-0.5, homeLabel:"USA -0.5", awayLabel:"PAR +0.5", homePayout:1.8, awayPayout:2.05 },
    simHomeWin:51, simCoverAH:49, marketCoverAH:53, edge:-4,
    notes:"USA co-host home advantage vs Paraguay's CONMEBOL quality. Very tight. DNB returns stake on draw.",
    rec:"slight", recLabel:"Lean PAR +0.5", recDetail:"Sim cover 51% for PAR +line — marginal edge to the underdog." },

  { id:"E1", stage:"GRP", date:"Jun 14", group:"Group E", venue:"Houston",
    home:"Germany", homeFlag:"🇩🇪", homeCode:"GER", homePlayers:["GER"],
    away:"Curaçao", awayFlag:"🇨🇼", awayCode:"CUR",
    homeML:-1800, awayML:2500,
    ah:{ line:-3.5, homeLabel:"GER -3.5", awayLabel:"CUR +3.5", homePayout:1.89, awayPayout:1.81 },
    simHomeWin:97, simCoverAH:27, marketCoverAH:49, edge:-22,
    notes:"Germany 97% win probability. Wirtz + Musiala vs WC +17,500 longshots. Win by 3+ is 72% likely.",
    rec:"strong", recLabel:"🔥 Back CUR +3.5", recDetail:"Underdog covers 73% — strong value on CUR." },

  { id:"F1", stage:"GRP", date:"Jun 14", group:"Group F", venue:"Dallas",
    home:"Netherlands", homeFlag:"🇳🇱", homeCode:"NED", homePlayers:["NED"],
    away:"Japan", awayFlag:"🇯🇵", awayCode:"JPN", awayPlayers:["JPN"],
    homeML:-130, awayML:310,
    ah:{ line:-0.5, homeLabel:"NED -0.5", awayLabel:"JPN +0.5", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:54, simCoverAH:44, marketCoverAH:51, edge:-7,
    notes:"NED 54% win. Van Dijk + Gakpo elite form. Japan giant-killers but NED width causes problems.",
    rec:"value", recLabel:"✓ Back JPN +0.5", recDetail:"Underdog covers 56% of the time — value on JPN +0.5." },

  { id:"G1", stage:"GRP", date:"Jun 15", group:"Group G", venue:"Seattle",
    home:"Belgium", homeFlag:"🇧🇪", homeCode:"BEL", homePlayers:["BEL"],
    away:"Egypt", awayFlag:"🇪🇬", awayCode:"EGY",
    homeML:-280, awayML:390,
    ah:{ line:-1, homeLabel:"BEL -1", awayLabel:"EGY +1.0", homePayout:2.27, awayPayout:1.69 },
    simHomeWin:67, simCoverAH:40, marketCoverAH:43, edge:-3,
    notes:"Belgium 67% win but only 46% to win by 2+. Egypt compact and disciplined defensively.",
    rec:"strong", recLabel:"🔥 Back EGY +1.0", recDetail:"Underdog covers 60% — strong value on EGY." },

  { id:"H1", stage:"GRP", date:"Jun 15", group:"Group H", venue:"Atlanta",
    home:"Spain", homeFlag:"🇪🇸", homeCode:"ESP", homePlayers:["ESP"],
    away:"Cape Verde", awayFlag:"🇨🇻", awayCode:"CPV",
    homeML:-1400, awayML:2800,
    ah:{ line:-2.5, homeLabel:"ESP -2.5", awayLabel:"CPV +2.5", homePayout:1.85, awayPayout:1.95 },
    simHomeWin:96, simCoverAH:71, marketCoverAH:50, edge:21,
    notes:"Spain 96% win vs +250,000 WC outsiders. Pedri, Rodri, Yamal — built to dominate. -2.5 cover 71%.",
    rec:"strong", recLabel:"🔥 ESP -2.5 STRONG VALUE", recDetail:"+21% edge. Spain's MID 95 vs weakest squad in tournament. Top confidence pick." },

  { id:"H2", stage:"GRP", date:"Jun 15", group:"Group H", venue:"Miami",
    home:"Saudi Arabia", homeFlag:"🇸🇦", homeCode:"KSA",
    away:"Uruguay", awayFlag:"🇺🇾", awayCode:"URU", awayPlayers:["URU"],
    homeML:420, awayML:-160,
    ah:{ line:1.25, homeLabel:"KSA +1.25", awayLabel:"URU -1.25", homePayout:1.82, awayPayout:2.02 },
    simHomeWin:60, simCoverAH:65, marketCoverAH:53, edge:12,
    notes:"Uruguay (Valverde, Núñez, Araújo) 60% win. -0.5 = just need Uruguay to win. Thin payout.",
    rec:"strong", recLabel:"🔥 Back KSA +1.25", recDetail:"Sim cover 65% — strong value laying KSA." },

  { id:"I1", stage:"GRP", date:"Jun 16", group:"Group I", venue:"East Rutherford NJ",
    home:"France", homeFlag:"🇫🇷", homeCode:"FRA", homePlayers:["FRA"],
    away:"Senegal", awayFlag:"🇸🇳", awayCode:"SEN", awayPlayers:["SEN"],
    homeML:-250, awayML:420,
    ah:{ line:-1, homeLabel:"FRA -1", awayLabel:"SEN +1.0", homePayout:1.8, awayPayout:2.05 },
    simHomeWin:72, simCoverAH:39, marketCoverAH:53, edge:-14,
    notes:"France ATK 94 + Mbappé speed vs Mendy GK 83. 72% win, 55% to cover -1 (win by 2+).",
    rec:"strong", recLabel:"🔥 Back SEN +1.0", recDetail:"Underdog covers 61% — strong value on SEN." },

  { id:"J1", stage:"GRP", date:"Jun 17", group:"Group J", venue:"Miami",
    home:"Argentina", homeFlag:"🇦🇷", homeCode:"ARG", homePlayers:["ARG"],
    away:"Algeria", awayFlag:"🇩🇿", awayCode:"ALG",
    homeML:-350, awayML:400,
    ah:{ line:-1.5, homeLabel:"ARG -1.5", awayLabel:"ALG +1.5", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:78, simCoverAH:34, marketCoverAH:51, edge:-17,
    notes:"Messi's final WC opener. Argentina EXP 96, ATK 93. -1.5 cover 57% probable. Maximum motivation.",
    rec:"strong", recLabel:"🔥 Back ALG +1.5", recDetail:"Underdog covers 66% — strong value taking ALG +1.5." },

  { id:"K1", stage:"GRP", date:"Jun 17", group:"Group K", venue:"Kansas City",
    home:"Portugal", homeFlag:"🇵🇹", homeCode:"POR", homePlayers:["POR"],
    away:"Congo DR", awayFlag:"🇨🇩", awayCode:"CGO",
    homeML:-400, awayML:550,
    ah:{ line:-1.5, homeLabel:"POR -1.5", awayLabel:"CGO +1.5", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:81, simCoverAH:61, marketCoverAH:50, edge:11,
    notes:"Portugal vs first-time WC qualifier. Leão + B.Fernandes in full flow. 81% win, 61% to cover -1.5.",
    rec:"value", recLabel:"✅ POR -1.5 GOOD VALUE", recDetail:"+11% edge — best value pick this round. Ronaldo wants to score. Full confidence." },

  { id:"L1", stage:"GRP", date:"Jun 17", group:"Group L", venue:"Boston",
    home:"England", homeFlag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", homeCode:"ENG", homePlayers:["ENG"],
    away:"Croatia", awayFlag:"🇭🇷", awayCode:"CRO", awayPlayers:["CRO"],
    homeML:-180, awayML:380,
    ah:{ line:-0.75, homeLabel:"ENG -0.75", awayLabel:"CRO +0.75", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:61, simCoverAH:52, marketCoverAH:50, edge:2,
    notes:"WC 2018 SF rematch. England 61% win. -0.75 returns half stake on 1-goal win. Bellingham vs Modrić.",
    rec:"slight", recLabel:"ENG -0.75 thin edge", recDetail:"+2% only — razor thin. Modrić's big-game experience makes this uncertain." },

  // ══════════════════════════════════════════════════════
  //  GROUP STAGE — ROUND 2 KEY MATCHES (Jun 18–22)
  // ══════════════════════════════════════════════════════

  { id:"C2", stage:"GRP", date:"Jun 19", group:"Group C", venue:"New York NJ",
    home:"Brazil", homeFlag:"🇧🇷", homeCode:"BRA", homePlayers:["BRA"],
    away:"Scotland", awayFlag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", awayCode:"SCO",
    homeML:-500, awayML:600,
    ah:{ line:-2, homeLabel:"BRA -2", awayLabel:"SCO +2", homePayout:1.85, awayPayout:1.95 },
    simHomeWin:88, simCoverAH:62, marketCoverAH:50, edge:12,
    notes:"Brazil vs Scotland. Vinícius in full flow. 88% win, 62% to win by 3+. Scotland +950 in group.",
    rec:"value", recLabel:"✅ BRA -2 GOOD VALUE", recDetail:"+12% edge. Vinícius vs Scotland defence — highly favourable matchup." },

  { id:"E2", stage:"GRP", date:"Jun 20", group:"Group E", venue:"Houston",
    home:"Germany", homeFlag:"🇩🇪", homeCode:"GER", homePlayers:["GER"],
    away:"Ecuador", awayFlag:"🇪🇨", awayCode:"ECU",
    homeML:-250, awayML:380,
    ah:{ line:-1, homeLabel:"GER -1", awayLabel:"ECU +1", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:68, simCoverAH:51, marketCoverAH:50, edge:1,
    notes:"Germany vs Ecuador. Stiffer test than R1. Wirtz still dominant but Ecuador resilient.",
    rec:"neutral", recLabel:"— Skip (marginal)", recDetail:"51% cover — barely above market. No meaningful edge." },

  { id:"F2", stage:"GRP", date:"Jun 20", group:"Group F", venue:"Dallas",
    home:"Netherlands", homeFlag:"🇳🇱", homeCode:"NED", homePlayers:["NED"],
    away:"Sweden", awayFlag:"🇸🇪", awayCode:"SWE",
    homeML:-200, awayML:420,
    ah:{ line:-1, homeLabel:"NED -1", awayLabel:"SWE +1.0", homePayout:2.12, awayPayout:1.76 },
    simHomeWin:63, simCoverAH:40, marketCoverAH:45, edge:-5,
    notes:"Netherlands vs Sweden. NED 63% win. Gakpo vs Swedish rearguard. -0.75 partial refund structure.",
    rec:"strong", recLabel:"🔥 Back SWE +1.0", recDetail:"Underdog covers 60% — strong value on SWE." },

  { id:"H3", stage:"GRP", date:"Jun 21", group:"Group H", venue:"Seattle",
    home:"Spain", homeFlag:"🇪🇸", homeCode:"ESP", homePlayers:["ESP"],
    away:"Saudi Arabia", awayFlag:"🇸🇦", awayCode:"KSA",
    homeML:-800, awayML:1200,
    ah:{ line:-2.5, homeLabel:"ESP -2.5", awayLabel:"KSA +2.5", homePayout:2.0, awayPayout:1.81 },
    simHomeWin:92, simCoverAH:20, marketCoverAH:48, edge:-28,
    notes:"Spain 92% win vs Saudi Arabia. Rodri + Pedri control will be total. -2 cover 67%.",
    rec:"strong", recLabel:"🔥 Back KSA +2.5", recDetail:"Underdog covers 80% — strong value on KSA." },

  { id:"I2", stage:"GRP", date:"Jun 22", group:"Group I", venue:"New York NJ",
    home:"France", homeFlag:"🇫🇷", homeCode:"FRA", homePlayers:["FRA"],
    away:"Iraq", awayFlag:"🇮🇶", awayCode:"IRQ",
    homeML:-1000, awayML:1800,
    ah:{ line:-2.5, homeLabel:"FRA -2.5", awayLabel:"IRQ +2.5", homePayout:2.08, awayPayout:1.81 },
    simHomeWin:95, simCoverAH:31, marketCoverAH:47, edge:-16,
    notes:"France vs Iraq (+7000 WC odds). Mbappé will be hungry. 95% win, 70% to win by 3+.",
    rec:"strong", recLabel:"🔥 Back IRQ +2.5", recDetail:"Underdog covers 69% — strong value on IRQ." },

  { id:"J2", stage:"GRP", date:"Jun 22", group:"Group J", venue:"Dallas",
    home:"Argentina", homeFlag:"🇦🇷", homeCode:"ARG", homePlayers:["ARG"],
    away:"Austria", awayFlag:"🇦🇹", awayCode:"AUT",
    homeML:-300, awayML:450,
    ah:{ line:-1, homeLabel:"ARG -1", awayLabel:"AUT +1.0", homePayout:2.17, awayPayout:1.75 },
    simHomeWin:75, simCoverAH:44, marketCoverAH:45, edge:-1,
    notes:"Argentina vs Austria. ARG in top gear after R1. Messi + Mac Allister vs organised Austria.",
    rec:"value", recLabel:"✓ Back AUT +1.0", recDetail:"Underdog covers 56% — value on AUT." },

  { id:"L2", stage:"GRP", date:"Jun 22", group:"Group L", venue:"Boston",
    home:"England", homeFlag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", homeCode:"ENG", homePlayers:["ENG"],
    away:"Ghana", awayFlag:"🇬🇭", awayCode:"GHA",
    homeML:-350, awayML:500,
    ah:{ line:-1.5, homeLabel:"ENG -1.5", awayLabel:"GHA +1.5", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:79, simCoverAH:58, marketCoverAH:50, edge:8,
    notes:"England vs Ghana. Bellingham + Kane + Saka — quality difference is massive. 58% to cover -1.5.",
    rec:"value", recLabel:"✅ ENG -1.5 VALUE", recDetail:"+8% edge. England's attack depth too much for Ghana. Solid mid-tournament pick." },

  // ══════════════════════════════════════════════════════
  //  KNOCKOUT STAGE — PROJECTED LINES
  // ══════════════════════════════════════════════════════

  { id:"R16_1", stage:"R16", date:"~Jul 2", group:"R16 Proj.", venue:"MetLife Stadium",
    home:"France", homeFlag:"🇫🇷", homeCode:"FRA", homePlayers:["FRA"],
    away:"Senegal", awayFlag:"🇸🇳", awayCode:"SEN", awayPlayers:["SEN"],
    homeML:-280, awayML:480,
    ah:{ line:-1, homeLabel:"FRA -1", awayLabel:"SEN +1", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:72, simCoverAH:54, marketCoverAH:50, edge:4,
    notes:"PROJECTED R16. France vs Senegal — group bracket path rematch. Knockout intensity tightens margins.",
    rec:"slight", recLabel:"FRA -1 slight edge (R16)", recDetail:"Knockout games tighter — simulation gives +4% edge. Smaller stake than group stage." },

  { id:"R16_2", stage:"R16", date:"~Jul 2", group:"R16 Proj.", venue:"Allegiant Stadium",
    home:"Germany", homeFlag:"🇩🇪", homeCode:"GER", homePlayers:["GER"],
    away:"USA", awayFlag:"🇺🇸", awayCode:"USA", awayPlayers:["USA"],
    homeML:-180, awayML:360,
    ah:{ line:-0.5, homeLabel:"GER -0.5", awayLabel:"USA +0.5", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:61, simCoverAH:61, marketCoverAH:50, edge:11,
    notes:"PROJECTED R16. Germany vs USA host nation. USA home crowd roaring but GER quality significant edge.",
    rec:"value", recLabel:"✅ GER -0.5 VALUE (R16)", recDetail:"+11% edge. Wirtz + Musiala vs Adams + Pulisic — quality gap favours Germany." },

  { id:"R16_3", stage:"R16", date:"~Jul 3", group:"R16 Proj.", venue:"Hard Rock Stadium",
    home:"Spain", homeFlag:"🇪🇸", homeCode:"ESP", homePlayers:["ESP"],
    away:"Morocco", awayFlag:"🇲🇦", awayCode:"MAR", awayPlayers:["MAR"],
    homeML:-200, awayML:420,
    ah:{ line:-0.75, homeLabel:"ESP -0.75", awayLabel:"MAR +0.75", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:63, simCoverAH:52, marketCoverAH:50, edge:2,
    notes:"PROJECTED R16. Spain vs Morocco — exact 2022 QF rematch (Morocco won on penalties). Tight.",
    rec:"neutral", recLabel:"— Skip (too close)", recDetail:"Morocco beat Spain in 2022. Psychological edge for Morocco. Sim shows only +2% — not worth it." },

  { id:"R16_4", stage:"R16", date:"~Jul 3", group:"R16 Proj.", venue:"AT&T Stadium",
    home:"Argentina", homeFlag:"🇦🇷", homeCode:"ARG", homePlayers:["ARG"],
    away:"Colombia", awayFlag:"🇨🇴", awayCode:"COL", awayPlayers:["COL"],
    homeML:-220, awayML:420,
    ah:{ line:-0.75, homeLabel:"ARG -0.75", awayLabel:"COL +0.75", homePayout:1.90, awayPayout:1.90 },
    simHomeWin:66, simCoverAH:55, marketCoverAH:50, edge:5,
    notes:"PROJECTED R16. Argentina vs Colombia Copa América 2024 final rematch. ARG won 1-0.",
    rec:"slight", recLabel:"ARG -0.75 slight edge (R16)", recDetail:"+5% at 1.90. L.Díaz dangerous but Emiliano Martínez neutralises. Small stake." },

  { id:"QF_1", stage:"QF", date:"~Jul 8", group:"QF Proj.", venue:"MetLife Stadium",
    home:"France", homeFlag:"🇫🇷", homeCode:"FRA", homePlayers:["FRA"],
    away:"Germany", awayFlag:"🇩🇪", awayCode:"GER", homePlayers:["GER"],
    homeML:-160, awayML:320,
    ah:{ line:-0.5, homeLabel:"FRA -0.5", awayLabel:"GER +0.5", homePayout:1.90, awayPayout:1.90 },
    simHomeWin:62, simCoverAH:62, marketCoverAH:50, edge:12,
    notes:"PROJECTED QF. France vs Germany — classic European clash. Mbappé vs Rüdiger. France 62% win.",
    rec:"value", recLabel:"✅ FRA -0.5 VALUE (QF)", recDetail:"+12% edge. France ATK 94 DEF 92 — all-round superiority. Solid QF play." },

  { id:"QF_2", stage:"QF", date:"~Jul 9", group:"QF Proj.", venue:"Rose Bowl",
    home:"Argentina", homeFlag:"🇦🇷", homeCode:"ARG", homePlayers:["ARG"],
    away:"Brazil", awayFlag:"🇧🇷", awayCode:"BRA", awayPlayers:["BRA"],
    homeML:-140, awayML:290,
    ah:{ line:0, homeLabel:"ARG 0 (DNB)", awayLabel:"BRA 0 (DNB)", homePayout:1.90, awayPayout:1.90 },
    simHomeWin:55, simCoverAH:55, marketCoverAH:50, edge:5,
    notes:"PROJECTED QF. Argentina vs Brazil — the Superclásico on WC stage. Emiliano Martínez makes the difference. Tightest QF.",
    rec:"slight", recLabel:"ARG DNB slight edge (QF)", recDetail:"+5% edge. Draw refunded. Messi vs Vinícius is the headline battle — take Argentina." },

  { id:"SF_1", stage:"SF", date:"~Jul 14", group:"SF Proj.", venue:"MetLife Stadium",
    home:"France", homeFlag:"🇫🇷", homeCode:"FRA", homePlayers:["FRA"],
    away:"Spain", awayFlag:"🇪🇸", awayCode:"ESP", awayPlayers:["ESP"],
    homeML:-120, awayML:240,
    ah:{ line:0, homeLabel:"FRA 0 (DNB)", awayLabel:"ESP 0 (DNB)", homePayout:1.90, awayPayout:1.90 },
    simHomeWin:57, simCoverAH:57, marketCoverAH:50, edge:7,
    notes:"PROJECTED SF1. France vs Spain — the marquee European clash. Mbappé vs Rodri. France 57% win.",
    rec:"slight", recLabel:"FRA DNB edge (SF)", recDetail:"+7% but SF games highly volatile. Only if sim and market align. Cautious approach." },

  { id:"SF_2", stage:"SF", date:"~Jul 15", group:"SF Proj.", venue:"Rose Bowl",
    home:"Argentina", homeFlag:"🇦🇷", homeCode:"ARG", homePlayers:["ARG"],
    away:"England", awayFlag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", awayCode:"ENG", awayPlayers:["ENG"],
    homeML:-160, awayML:320,
    ah:{ line:-0.5, homeLabel:"ARG -0.5", awayLabel:"ENG +0.5", homePayout:1.88, awayPayout:1.92 },
    simHomeWin:63, simCoverAH:63, marketCoverAH:50, edge:13,
    notes:"PROJECTED SF2. Argentina vs England. Messi vs Bellingham. ARG 63% win — Emiliano Martínez GK 92 decisive.",
    rec:"value", recLabel:"✅ ARG -0.5 VALUE (SF)", recDetail:"+13% edge. Argentina's KO experience (EXP 96) is unmatched at this stage." },

  { id:"F1", stage:"F", date:"Jul 19", group:"Final", venue:"MetLife Stadium NJ",
    home:"France", homeFlag:"🇫🇷", homeCode:"FRA", homePlayers:["FRA"],
    away:"Argentina", awayFlag:"🇦🇷", awayCode:"ARG", awayPlayers:["ARG"],
    homeML:-130, awayML:260,
    ah:{ line:0, homeLabel:"FRA 0 (DNB)", awayLabel:"ARG 0 (DNB)", homePayout:1.90, awayPayout:1.90 },
    simHomeWin:54, simCoverAH:54, marketCoverAH:50, edge:4,
    notes:"PROJECTED FINAL. France vs Argentina — 2022 Final rematch. France 54% win. Mbappé vs Emiliano Martínez is the decisive duel.",
    rec:"slight", recLabel:"FRA DNB (Final — slim)", recDetail:"+4% edge only. Finals are coin-flip territory. Enjoy the match — small stake if anything." },
];

const REC_CONFIG = {
  strong:  { color:"#22c55e", bg:"rgba(34,197,94,.12)", border:"rgba(34,197,94,.3)" },
  value:   { color:"#4ade80", bg:"rgba(74,222,128,.08)", border:"rgba(74,222,128,.25)" },
  slight:  { color:"#facc15", bg:"rgba(250,204,21,.06)", border:"rgba(250,204,21,.2)" },
  neutral: { color:"#6b7f99", bg:"rgba(107,127,153,.05)", border:"rgba(107,127,153,.15)" },
  avoid:   { color:"#f97316", bg:"rgba(249,115,22,.08)", border:"rgba(249,115,22,.25)" },
};

function waterLabel(p) {
  if (p >= 1.93) return { txt: p + " 水位 ▲", col:"#22c55e" };
  if (p >= 1.88) return { txt: p + " 水位 ●", col:"#facc15" };
  return { txt: p + " 水位 ▼", col:"#f97316" };
}

const STAGE_ORDER = { GRP:0, R32:1, R16:2, QF:3, SF:4, F:5 };

// ═══════════════════════════════════════════════
//  TOP SCORER / GOLDEN BOOT DATA
//  Odds: Bet365 / FanDuel (Jun 8 2026, decimal)
// ═══════════════════════════════════════════════
const TOP_SCORERS = [
  { rank:1, name:"Kylian Mbappé",    flag:"🇫🇷", team:"France",    code:"FRA", pos:"FWD",
    decimal:7.00, american:"+600", dec_alt:"7.00",
    col1:"#003189", col2:"#c8102e", init:"KM",
    jersey:"10", club:"Real Madrid",
    simNote:"France projected champion (32.6%) · 7 games if finals run · 2022 Golden Boot winner (8 goals)",
    stat1:"12 WC goals", stat2:"8 goals in 2022", stat3:"7 of 7 qualifying scores",
    edge:"strong" },
  { rank:2, name:"Harry Kane",       flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", team:"England",   code:"ENG", pos:"FWD",
    decimal:8.00, american:"+700", dec_alt:"8.00",
    col1:"#cf081f", col2:"#012169", init:"HK",
    jersey:"9", club:"Bayern Munich",
    simNote:"England projected SF (37.4%) · First-choice penalty taker · 2018 Golden Boot (6 goals in Russia)",
    stat1:"7 WC goals", stat2:"9 ENG goals qualifying", stat3:"36 Bundesliga goals 24-25",
    edge:"value" },
  { rank:3, name:"Erling Haaland",   flag:"🇳🇴", team:"Norway",    code:"NOR", pos:"FWD",
    decimal:15.00, american:"+1400", dec_alt:"15.00",
    col1:"#c8102e", col2:"#003087", init:"EH",
    jersey:"9", club:"Man City",
    simNote:"Norway outside top 16 · Haaland's 55/48 intl record elite · Needs deep Norway run to win boot",
    stat1:"55 Norway goals (48 apps)", stat2:"105 goals Man City", stat3:"First WC",
    edge:"slight" },
  { rank:4, name:"Lionel Messi",     flag:"🇦🇷", team:"Argentina", code:"ARG", pos:"FWD",
    decimal:13.00, american:"+1200", dec_alt:"13.00",
    col1:"#74acdf", col2:"#ffffff", init:"LM",
    jersey:"10", club:"Inter Miami",
    simNote:"Argentina projected finalist (27.7%) · Last WC — maximum motivation · 2022 Golden Ball winner",
    stat1:"13 WC goals", stat2:"2022 Golden Ball", stat3:"7 games if deep",
    edge:"value" },
  { rank:5, name:"Lamine Yamal",     flag:"🇪🇸", team:"Spain",     code:"ESP", pos:"FWD",
    decimal:15.00, american:"+1400", dec_alt:"15.00",
    col1:"#c8102e", col2:"#f1bf00", init:"LY",
    jersey:"19", club:"Barcelona",
    simNote:"Spain projected SF (66.7%) · Only 18 · Goals improving rapidly · 2024 Euro star",
    stat1:"18 yrs old", stat2:"Euro 2024 winner", stat3:"Spain projected SF",
    edge:"slight" },
  { rank:6, name:"Mikel Oyarzabal",  flag:"🇪🇸", team:"Spain",     code:"ESP", pos:"FWD",
    decimal:19.00, american:"+1800", dec_alt:"19.00",
    col1:"#c8102e", col2:"#f1bf00", init:"MO",
    jersey:"7", club:"Real Sociedad",
    simNote:"Spain's #9 starting striker · 1 goal per 74 min in qualifying · Benefits from Pedri+Yamal service",
    stat1:"1 goal / 74 min qualifying", stat2:"Spain projected SF", stat3:"Underrated long shot",
    edge:"slight" },
  { rank:7, name:"Cristiano Ronaldo",flag:"🇵🇹", team:"Portugal",  code:"POR", pos:"FWD",
    decimal:21.00, american:"+2000", dec_alt:"21.00",
    col1:"#006600", col2:"#c8102e", init:"CR",
    jersey:"7", club:"Al Nassr",
    simNote:"Portugal projected QF (33.4%) · At 41, role uncertain · Last WC chance creates motivation ceiling",
    stat1:"9 WC goals career", stat2:"At 41 years old", stat3:"Last shot at glory",
    edge:"neutral" },
  { rank:8, name:"Vinícius Jr.",     flag:"🇧🇷", team:"Brazil",    code:"BRA", pos:"FWD",
    decimal:31.00, american:"+3000", dec_alt:"31.00",
    col1:"#009c3b", col2:"#fedf00", init:"VJ",
    jersey:"7", club:"Real Madrid",
    simNote:"Brazil projected QF (28.2%) · Most dangerous winger in world · 31 La Liga goals 24-25",
    stat1:"31 La Liga goals 24-25", stat2:"Brazil projected QF", stat3:"Pure pace threat",
    edge:"neutral" },
  { rank:9, name:"Lautaro Martínez", flag:"🇦🇷", team:"Argentina", code:"ARG", pos:"FWD",
    decimal:36.00, american:"+3500", dec_alt:"36.00",
    col1:"#74acdf", col2:"#ffffff", init:"LM",
    jersey:"22", club:"Inter Milan",
    simNote:"Argentina projected finalist · Messi's strike partner · Serie A top scorer — clinical inside the box",
    stat1:"26 Serie A goals 24-25", stat2:"Argentina projected finalist", stat3:"Messi feeder",
    edge:"neutral" },
  { rank:10, name:"Bukayo Saka",     flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", team:"England",   code:"ENG", pos:"FWD",
    decimal:41.00, american:"+4000", dec_alt:"41.00",
    col1:"#cf081f", col2:"#012169", init:"BS",
    jersey:"7", club:"Arsenal",
    simNote:"England projected SF · 3 WC goals in 2022 in only 4 apps · 19+16 assist season 24-25",
    stat1:"19 goals + 16 assists 24-25", stat2:"3 WC goals in 2022", stat3:"England projected SF",
    edge:"neutral" },
  { rank:11, name:"Cody Gakpo",      flag:"🇳🇱", team:"Netherlands",code:"NED", pos:"FWD",
    decimal:17.00, american:"+1600", dec_alt:"17.00",
    col1:"#ff6600", col2:"#ffffff", init:"CG",
    jersey:"11", club:"Liverpool",
    simNote:"Netherlands projected QF (10.3%) · 25 PL goals 24-25 · 3 WC goals in Qatar 2022",
    stat1:"3 WC goals 2022", stat2:"25 PL goals 24-25", stat3:"Netherlands projected QF",
    edge:"slight" },
  { rank:12, name:"Rafael Leão",     flag:"🇵🇹", team:"Portugal",  code:"POR", pos:"FWD",
    decimal:26.00, american:"+2500", dec_alt:"26.00",
    col1:"#006600", col2:"#c8102e", init:"RL",
    jersey:"22", club:"AC Milan",
    simNote:"Portugal projected QF · Portugal's explosive new spearhead post-Ronaldo · Pace causes any defence problems",
    stat1:"Portugal's new #1 attacker", stat2:"Portugal projected QF", stat3:"Serie A standout",
    edge:"neutral" },
];

// WDW odds embedded per match (added to existing MATCHES)
// Format: [home decimal, draw decimal, away decimal]
const WDW_ODDS = {
  A1:[1.28,6.50,14.00], A2:[2.05,3.50,3.60],
  C1:[1.32,5.50,11.00], D1:[2.10,3.30,3.80],
  E1:[1.04,18.00,50.00], F1:[2.20,3.40,3.30],
  G1:[1.44,4.80,7.50], H1:[1.06,16.00,45.00],
  H2:[4.50,3.60,1.70], I1:[1.62,3.80,5.60],
  J1:[1.32,5.50,10.00], K1:[1.25,6.00,12.00],
  L1:[1.72,3.75,4.80], C2:[1.08,14.00,34.00],
  E2:[1.65,3.70,5.40], F2:[1.75,3.75,4.60],
  H3:[1.10,12.00,26.00], I2:[1.08,14.00,38.00],
  J2:[1.38,5.00,8.50], L2:[1.30,5.50,10.00],
  R16_1:[1.62,3.80,5.60], R16_2:[1.70,3.60,5.00],
  R16_3:[1.80,3.60,4.80], R16_4:[1.75,3.80,4.60],
  QF_1:[1.72,3.60,4.80], QF_2:[1.90,3.40,4.20],
  SF_1:[1.95,3.40,4.00], SF_2:[1.75,3.50,4.60],
  F1:[1.95,3.40,4.10],
};

// ═══════════════════════════════════════════════
//  PLAYER PHOTOS — Wikipedia Commons
//  Browser fetches these directly (CORS-safe)
//  Falls back to SVG avatar if image fails
// ═══════════════════════════════════════════════
const PLAYER_PHOTOS = {
  "Kylian Mbappé":    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Kylian_Mbapp%C3%A9_2019-10-11_1.jpg/320px-Kylian_Mbapp%C3%A9_2019-10-11_1.jpg",
  "Harry Kane":        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Harry_Kane_2023.jpg/320px-Harry_Kane_2023.jpg",
  "Erling Haaland":    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Erling_Haaland_2023.jpg/320px-Erling_Haaland_2023.jpg",
  "Lionel Messi":      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Lionel_Messi_20180626_%28cropped%29.jpg/320px-Lionel_Messi_20180626_%28cropped%29.jpg",
  "Lamine Yamal":      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Lamine_Yamal_2024.jpg/320px-Lamine_Yamal_2024.jpg",
  "Mikel Oyarzabal":   "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Mikel_Oyarzabal_2022_%28cropped%29.jpg/320px-Mikel_Oyarzabal_2022_%28cropped%29.jpg",
  "Cristiano Ronaldo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Cristiano_Ronaldo_2019_%28cropped%29.jpg/320px-Cristiano_Ronaldo_2019_%28cropped%29.jpg",
  "Vinícius Jr.":      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Vin%C3%ADcius_J%C3%BAnior_2024_%28cropped%29.jpg/320px-Vin%C3%ADcius_J%C3%BAnior_2024_%28cropped%29.jpg",
  "Lautaro Martínez":  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Lautaro_Mart%C3%ADnez_2023.jpg/320px-Lautaro_Mart%C3%ADnez_2023.jpg",
  "Bukayo Saka":       "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Bukayo_Saka_2022_%28cropped%29.jpg/320px-Bukayo_Saka_2022_%28cropped%29.jpg",
  "Cody Gakpo":        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Cody_Gakpo_2023.jpg/320px-Cody_Gakpo_2023.jpg",
  "Rafael Leão":       "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Rafael_Le%C3%A3o_2023.jpg/320px-Rafael_Le%C3%A3o_2023.jpg",
};
